apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-addons
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/cluster-addons
  prune: true
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: appmesh-controller
      namespace: appmesh-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: mesh-addons
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  dependsOn:
    - name: cluster-addons
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/mesh-addons
  prune: true
  validation: client
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: appmesh-gateway
      namespace: appmesh-system
    - apiVersion: helm.toolkit.fluxcd.io/v1beta1
      kind: HelmRelease
      name: flagger
      namespace: appmesh-system
